### ISSUE TITLE
Incorrect tag display

### ISSUE THREAD

**Issue by lwy1010** [glushchenko/fsnotes#1131]
**Describe the bug**

It seems that the app thinks of hex color as a tag. I write my css code demo in code block, just like this:

```css
:root {
  --bg: #fff;
  --text-color: #222;
  --link-color: #0033cc;
}
```

but the app thinks of hex color as a tag(such as #0033cc) and display it on the sidebar's tags menu. 

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.10.1
